appVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce # instance of storage can be used by a single node
    # ReadOnlyMany - multiple nodes can read from this
    # ReadWriteMany - can be read and written to by many nodes
  resources:
    requests:
      storage: 2Gi # a storage option that is 2Gb of space